# Generated by Django 5.2.1 on 2025-06-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_remove_teacher_assigned_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='assigned_class_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
