# Generated by Django 5.2.1 on 2025-06-05 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='assigned_class_id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='assigned_class_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='assigned_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_app.classroom'),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
